import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:launchpad_app/extensions/json_typedef.dart';
import 'package:launchpad_app/services/firebase_gemini/gemini_service.dart';
import 'package:launchpad_app/services/firebase_remote_config/remote_config_service.dart';
import 'package:launchpad_app/services/image_generation/image_generation_service.dart';
import 'package:launchpad_app/services/image_generation/models/generated_image.dart';
import 'package:launchpad_app/services/project/models/achievement.dart';
import 'package:launchpad_app/services/project/models/how_to_step.dart';
import 'package:launchpad_app/services/project/models/how_to_supply.dart';
import 'package:launchpad_app/services/project/models/how_to_tip.dart';
import 'package:launchpad_app/services/project/models/how_to_tool.dart';
import 'package:launchpad_app/services/project/project.dart';
import 'package:launchpad_app/services/uuid/uuid_generator.dart';

/// Represents a project, derived from a [Project] object, that is augmented with additional data.
///
/// The [Project] class represents a project generated by an AI system from JSON conforming to the HowTo schema from
/// schema.org. This class represents an extension of that class, with additional data that is not part of the HowTo
/// schema. This class is used to represent projects that have been augmented with additional data, such as images
/// and links to sites from which tools and materials can be purchased. This additional data is used to enhance the
/// user experience when viewing the project by providing a richer project description.
///
/// The augmentations this class provides are:
/// - An image representing the project, generated using generative AI services.
/// - A list of achievements that can be unlocked after completing particularly important or challenging steps in the
///   project.
// ignore_for_file: always_put_required_named_parameters_first
class AugmentedProject extends Project {
  /// A unique identifier for the project.
  final String? id;

  /// The URL of an image representing the project. This image is created using generative AI services.
  final GeneratedImage? projectImage;

  /// A list of [Achievement]s that can be unlocked after completing particularly important or challenging steps in the
  /// project.
  final List<Achievement> achievements;

  /// Creates an instance of [AugmentedProject].
  AugmentedProject._({
    this.id,
    required super.name,
    required super.description,
    required super.steps,
    super.tools,
    super.supplies,
    super.tips,
    required this.projectImage,
    required this.achievements,
  });

  /// Returns an instance of [AugmentedProject] from a [Project] by making additional calls to asynchronous services.
  ///
  /// This method plays a similar role to a factory constructor, but it is asynchronous and makes additional calls to
  /// services to augment the project with additional data. This method is used to create an instance of
  /// [AugmentedProject] from a [Project] object by making additional calls to services to augment the project with
  /// additional data.
  static Future<AugmentedProject> fromProject(Project project) async {
    // Create a unique identifier for the project, which is random UUID.
    final String id = UuidGenerator.generateUuid();

    // The Firebase Remote Config service is used to configure various options for project augmentation.
    final RemoteConfigService remoteConfigService = RemoteConfigService();

    // Get an image for the project, as long as the capability is enabled in Firebase Remote Config.
    final GeneratedImage? projectImage;
    if (remoteConfigService.shouldGenerateCoverImages()) {
      // If the capability is enabled, get an image for the project.
      projectImage = await _getProjectImage(project);
    } else {
      // If the capability is disabled, set the project image to null.
      projectImage = null;
    }

    // Generate a list of achievements for the project.
    final List<Achievement> achievements = await _getAchievements(project.steps);

    // Construct the augmented project.
    return AugmentedProject._(
      id: id,
      name: project.name,
      description: project.description,
      steps: project.steps,
      tools: project.tools,
      supplies: project.supplies,
      tips: project.tips,
      projectImage: projectImage,
      achievements: achievements,
    );
  }

  /// Gets an image representing the project using generative AI services.
  ///
  /// This image is intended to be used as a cover image for the project. The image is generated based on the project
  /// description. If the image generation fails, the function returns null.
  static Future<GeneratedImage?> _getProjectImage(Project project) async {
    try {
      // Create a prompt for the image generation service based on the project contents.
      final String prompt = ImageGenerationService.buildPromptFromProject(project);

      // Get the current user.
      final User? user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        throw Exception('User is null');
      }

      // Get the App Check token.
      final String? appCheckToken = await FirebaseAppCheck.instance.getToken();
      if (appCheckToken == null || appCheckToken.isEmpty) {
        throw Exception('App Check token is null');
      }

      // Get an image for the project using generative AI services.
      final ImageGenerationService imageGenerationService = ImageGenerationService(user);
      final GeneratedImage projectImage = await imageGenerationService.generateImage(
        appCheckToken: appCheckToken,
        prompt: prompt,
      );

      return projectImage;
    } catch (e) {
      debugPrint('Failed to generate image for project with exception, $e');

      return null;
    }
  }

  /// Gets a list of achievements that can be unlocked after completing particularly important or challenging steps in
  /// the project.
  ///
  /// To generate achievements for a project, Gemini is used to analyze the project steps and determine which steps are
  /// particularly important or challenging. It then creates a list of achievements based on these steps.
  ///
  /// The achievements themselves are represented as a JSON array, where each element in the array is a JSON object
  /// containing information about an individual achievement. These JSON objects include the following fields:
  /// - `name` - The name of the achievement.
  /// - `description` - A description of the achievement.
  /// - `stepId` - The ID of the step that must be completed to unlock the achievement.
  ///
  /// So, for example, an achievement might look like this:
  ///
  /// ```json
  /// {
  ///  "name": "Master Craftsman",
  ///  "description": "Complete the final step in the project.",
  ///  "stepId": "abc123"
  ///  }
  ///  ```
  static Future<List<Achievement>> _getAchievements(List<HowToStep> steps) async {
    // Generate a list of achievements for the project.
    final List<Achievement> achievements = await GeminiService.generateAchievements(
      steps: steps,
    );

    return achievements;
  }

  /// Returns an [AugmentedProject] object from a JSON object.
  ///
  /// This function works in a similar way to a factory constructor. However, because getting the image URL from the
  /// Firebase backend is an asynchronous operation, which is not allowed in a factory constructor, this function is
  /// used instead.
  ///
  /// This function is typically used when retrieving a project from the Launchpad Firestore backend. The JSON objects
  /// returned from the backend are in an extended format based on the HowTo schema from schema.org. The standard schema
  /// has been augmented with additional fields, such as the project image URL.
  static Future<AugmentedProject> fromJson(JSONObject json) async {
    // Get the project ID.
    final String? id = json['projectId'] as String?;

    // Create a Project object from the JSON object.
    final Project project = Project.fromJson(json);

    // Get the project image from the JSON object.
    final JSONObject? projectImageJson = json['projectImage'] as JSONObject?;
    final GeneratedImage? projectImage = projectImageJson != null ? GeneratedImage.fromJson(projectImageJson) : null;

    // Get the list of achievements from the JSON object.
    final JSONArray achievementsJson = json['achievements'] as JSONArray;
    final List<Achievement> achievements =
        achievementsJson.map((achievementJson) => Achievement.fromJson(achievementJson as JSONObject)).toList();

    // Create an AugmentedProject object from the Project object.
    return AugmentedProject._(
      id: id,
      name: project.name,
      description: project.description,
      steps: project.steps,
      tools: project.tools,
      supplies: project.supplies,
      tips: project.tips,
      projectImage: projectImage,
      achievements: achievements,
    );
  }

  /// Creates a JSON representation of the augmented project. This JSON object is an extended version of the HowTo
  /// schema from schema.org. In addition to the fields defined for the HowTo schema, this JSON object includes the
  /// project image URL.
  JSONObject toJson() {
    return {
      'projectId': id,
      'name': name,
      'description': description,
      'projectImage': projectImage?.toJson(),
      'steps': steps.map((HowToStep step) => step.toJson()).toList(),
      'tools': tools?.map((HowToTool tool) => tool.toJson()).toList(),
      'supplies': supplies?.map((HowToSupply supply) => supply.toJson()).toList(),
      'tips': tips?.map((HowToTip tip) => tip.toJson()).toList(),
      'achievements': achievements.map((Achievement achievement) => achievement.toJson()).toList(),
    };
  }

  /// Creates a copy of this [AugmentedProject] with the given fields replaced with new values.
  ///
  /// This method is used to create a new [AugmentedProject] object with the same values as this object, except for the
  /// fields that are passed as arguments. This method is useful when updating the project data in the database.
  AugmentedProject copyWith({
    String? name,
    String? description,
    List<HowToStep>? steps,
    List<HowToTool>? tools,
    List<HowToSupply>? supplies,
    List<HowToTip>? tips,
    GeneratedImage? projectImage,
  }) {
    return AugmentedProject._(
      id: id,
      name: name ?? this.name,
      description: description ?? this.description,
      steps: steps ?? this.steps,
      tools: tools ?? this.tools,
      supplies: supplies ?? this.supplies,
      tips: tips ?? this.tips,
      projectImage: projectImage ?? this.projectImage,
      achievements: achievements,
    );
  }
}
