import 'package:launchpad_app/extensions/json_typedef.dart';
import 'package:launchpad_app/services/image_generation/models/generated_image_data.dart';

/// Represents an image generated by an AI model.
///
/// This class is used to represent an image generated by an AI model. Currently, images are generated using the
/// Generations API from OpenAI. However, when APIs are publicly available to perform image generation with
/// Google Gemini models, especially those available through the Firebase Gemini service, this class will be updated
/// to reflect the new implementation.
class GeneratedImage {
  /// A timestamp for when the image was generated, as a Unix epoch timestamp.
  final int timestamp;

  /// Data representing the generated image.
  final GeneratedImageData data;

  /// Creates a [GeneratedImage].
  GeneratedImage(
    this.timestamp,
    this.data,
  );

  /// Creates a [GeneratedImage] from a JSON object.
  factory GeneratedImage.fromJson(JSONObject json) {
    return GeneratedImage(
      json['created'] as int,
      GeneratedImageData.fromJson(json['data'] as JSONArray),
    );
  }

  /// Converts the [GeneratedImage] to a JSON object.
  JSONObject toJson() {
    return {
      'created': timestamp,
      'data': data.toJson(),
    };
  }
}
