name: presentation
description: "A presentation and demonstration of the Launchpad app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  # Contains a collection of cool and beautiful text animations.
  animated_text_kit: ^4.2.2
  # Protects backend resources by ensuring requests originate from this app.
  firebase_app_check: ^0.3.0+3
  # Flutter Firebase core plugin that enables all other Firebase services.
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  # Provides localization support.
  flutter_localizations:
    sdk: flutter
  # Handles internationalized/localized messages and other data types.
  intl: any
  # The Launchpad app, allowing the app itself to be embedded in this presentation.
  launchpad_app:
    path: ../../launchpad_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter.
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/introduction_images/
    - assets/profile_pictures/

  fonts:
    - family: KodeMono
      fonts:
        - asset: assets/fonts/KodeMono-VariableFont_wght.ttf