// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4vxq-YVEd6-MPdqABAfs9HpgcmO96K7w',
    appId: '1:366186287911:web:774aeb2fa6157454cb8f02',
    messagingSenderId: '366186287911',
    projectId: 'gadgetron-23712',
    authDomain: 'gadgetron-23712.firebaseapp.com',
    storageBucket: 'gadgetron-23712.appspot.com',
    measurementId: 'G-0NCNXCW9XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BD_LYyZdVRms6YMXH3No-wwhXphU8gY',
    appId: '1:366186287911:android:ca9c696d999f528ecb8f02',
    messagingSenderId: '366186287911',
    projectId: 'gadgetron-23712',
    storageBucket: 'gadgetron-23712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_82NE6a_NpOJp77FhNdqH0_8UCTEDPE',
    appId: '1:366186287911:ios:4740c6eaea4ab31dcb8f02',
    messagingSenderId: '366186287911',
    projectId: 'gadgetron-23712',
    storageBucket: 'gadgetron-23712.appspot.com',
    iosBundleId: 'com.splendidendeavors.gadgetron.gadgetronApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_82NE6a_NpOJp77FhNdqH0_8UCTEDPE',
    appId: '1:366186287911:ios:4740c6eaea4ab31dcb8f02',
    messagingSenderId: '366186287911',
    projectId: 'gadgetron-23712',
    storageBucket: 'gadgetron-23712.appspot.com',
    iosBundleId: 'com.splendidendeavors.gadgetron.gadgetronApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4vxq-YVEd6-MPdqABAfs9HpgcmO96K7w',
    appId: '1:366186287911:web:9c8cc8b19484d5e1cb8f02',
    messagingSenderId: '366186287911',
    projectId: 'gadgetron-23712',
    authDomain: 'gadgetron-23712.firebaseapp.com',
    storageBucket: 'gadgetron-23712.appspot.com',
    measurementId: 'G-098FR6FLS2',
  );

}