// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTiDcsxltRnBff_CLO19eKMbDzY5C3xo',
    appId: '1:1060418886631:web:8643d410953e026169fb42',
    messagingSenderId: '1060418886631',
    projectId: 'launchpad-d344d',
    authDomain: 'launchpad-d344d.firebaseapp.com',
    storageBucket: 'launchpad-d344d.appspot.com',
    measurementId: 'G-ZP28789ECG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDode7rPqUaXqckzRO5PvQrTmSw0aO9F-s',
    appId: '1:1060418886631:android:f795f61f1a4fb08b69fb42',
    messagingSenderId: '1060418886631',
    projectId: 'launchpad-d344d',
    storageBucket: 'launchpad-d344d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQMq05VoMKlwJJkKOR7CQJQmhPqm03nXw',
    appId: '1:1060418886631:ios:8b3c62be11a694e969fb42',
    messagingSenderId: '1060418886631',
    projectId: 'launchpad-d344d',
    storageBucket: 'launchpad-d344d.appspot.com',
    iosBundleId: 'com.splendidendeavors.launchpad.launchpadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQMq05VoMKlwJJkKOR7CQJQmhPqm03nXw',
    appId: '1:1060418886631:ios:8b3c62be11a694e969fb42',
    messagingSenderId: '1060418886631',
    projectId: 'launchpad-d344d',
    storageBucket: 'launchpad-d344d.appspot.com',
    iosBundleId: 'com.splendidendeavors.launchpad.launchpadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTiDcsxltRnBff_CLO19eKMbDzY5C3xo',
    appId: '1:1060418886631:web:f4d6821ee267525069fb42',
    messagingSenderId: '1060418886631',
    projectId: 'launchpad-d344d',
    authDomain: 'launchpad-d344d.firebaseapp.com',
    storageBucket: 'launchpad-d344d.appspot.com',
    measurementId: 'G-PDEGP2GY3F',
  );
}
