import 'package:gadgetron_app/screens/project_explore/project_explore_view.dart';

/// An enumeration of "roles" for messages in a multi-turn conversation with a Gemini model..
enum MessageRole {
  /// A message generated by the Gemini model.
  model('model'),

  /// A message provided by the user.
  user('user');

  /// The identifier for the role. This identifier is used by the [ChatMessage] class to determine how to display the
  /// message.
  final String identifier;

  const MessageRole(this.identifier);
}