include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    omit_local_variable_types: false
    prefer_int_literals: false