name: gadgetron_app
description: "Search for parts, build electronics, get troubleshooting help, make it so."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Provides localization support.
  flutter_localizations:
    sdk: flutter
  # Handles internationalized/localized messages and other data types.
  intl: any

dev_dependencies:
  # Flutter Firebase plugin.
  firebase_core: ^3.1.1
  # Lint rules for Dart and Flutter.
  flutter_lints: ^3.0.0
  # Provide automated testing tools.
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter.
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
  fonts:
    - family: KodeMono
      fonts:
        - asset: assets/fonts/KodeMono-VariableFont_wght.ttf