name: gadgetron_app
description: "Search for parts, build electronics, get troubleshooting help, make it so."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # Protects backend resources by ensuring requests originate from this app.
  firebase_app_check: ^0.3.0+2
  # Firebase Auth services for authentication flows using Firebase.
  firebase_auth: ^5.1.1
  # Flutter Firebase core plugin that enables all other Firebase services.
  firebase_core: ^3.1.1
  # Flutter plugin for Firebase Remote Config.
  firebase_remote_config: ^5.0.2
  # Firebase Vertex AI SDK.
  #firebase_vertexai: ^0.2.2+1
  # There is currently an issue with the Firebase Vertex AI SDK related to the way multi-turn
  # conversation history is handled. This branch contains a fix for this issue and this
  # dependency will be updated once the fix is merged into the master branch of the Flutterfire
  # repository.
  firebase_vertexai:
    git:
      url: https://github.com/Toglefritz/flutterfire.git
      ref: fix/update-chat-history
      path: packages/firebase_vertexai/firebase_vertexai
  # Flutter SDK
  flutter:
    sdk: flutter
  # Provides localization support.
  flutter_localizations:
    sdk: flutter
  # A Markdown renderer for Flutter.
  flutter_markdown: ^0.7.3
  # Provides infrastructure for signing in with a Google account.
  google_sign_in: ^6.2.1
  # Handles internationalized/localized messages and other data types.
  intl: any

dev_dependencies:
  # Lint rules for Dart and Flutter.
  flutter_lints: ^3.0.0
  # Provide automated testing tools.
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter.
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
  fonts:
    - family: KodeMono
      fonts:
        - asset: assets/fonts/KodeMono-VariableFont_wght.ttf